blank_issues_enabled: false
contact_links:
  - name: 📬 Discord Support
    url: https://discord.gg/visual-v
    about: Du brauchst Hilfe oder möchtest direkt mit dem Team sprechen? Dann nutze unseren Discord-Support!
